FROM php:8.1-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions imagick zip mysqli gd exif intl
RUN usermod -a -G root www-data
# Install MySQLi
#RUN apt-get update -y && apt-get install -y sendmail libpng-dev
#RUN apt-get update && apt-get install -y \
#    libmagickwand-dev --no-install-recommends \
#    && pecl install imagick \
#	&& docker-php-ext-enable imagick
#RUN apt-get update && apt-get install -y \
#    zlib1g-dev \
#    libzip-dev \
#    && docker-php-ext-install zip
#RUN docker-php-ext-install mysqli
# RUN docker-php-ext-install mbstring
#RUN docker-php-ext-install gd
#RUN docker-php-ext-install exif
# RUN docker-php-ext-install install
