version: '3'

services:
  web:
    build: ./wordpress
    image: gtctek/wordpress:latest
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html
    depends_on:
      - mariadb
    #extra_hosts:
      # Check the hosts file on the local machine for the
      # following lines and use the same IP address:
      # Added by Docker Desktop
      # 192.168.1.114 host.docker.internal
      # 192.168.1.114 gateway.docker.internal
      # - "localhost:192.168.1.114"
    networks:
      - dev-env
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - dev-env
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'r00tp4ssw0rd'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'w0rdpr3ss'
      MYSQL_DATABASE: 'wordpress'
    volumes:
      - mysqldata-nems:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev-env
volumes:
  mysqldata-nems: {}
networks:
  dev-env: {}